version: '3'
services:
  eurekaservice:
    build: ServiceRegistry
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - network-eureka 
  clientservice:
    build: GestionClient
    container_name: client-server
    ports:
      - "8081:8081"
    networks:
      - network-eureka
  personnelservice:
    build: GestionPersonnels
    container_name: personnels-server
    ports:
      - "8082:8082"
    networks:
      - network-eureka
  economatservice:
    build: GestionStockEconomat
    container_name: economat-server
    ports:
      - "8889:8889"
    networks:
      - network-eureka
  roomservice:
    build: GestionRoom
    container_name: room-server
    ports:
      - "8899:8899"
    networks:
      - network-eureka
      
  foodservice:
    build: GestionFood
    container_name: food-server
    ports:
      - "9001:9001"
    networks:
      - network-eureka
    depends_on:
      - eurekaservice
  gatewayservice:
    build: Gateway
    container_name: gateway-server
    ports:
      - "8888:8888"
    networks:
      - network-eureka
    links:
      - eurekaservice:eureka
      - clientservice:client
      - personnelservice:personnel
      - economatservice:economat
      - roomservice:room
      - foodservice:food
    depends_on:
      - eurekaservice

networks:
  network-eureka:
